                                               
obratFunc = "Ak chcete zacat, zadajte cislo pred pozadovanou funkciou.\n" + ...
    "-------------------------------------------------------------\n" + ...
    "1 - Urobit graf\n" + ...
    "2 - Nakreslite median\n" + ...
    "3 - Zobrazit pocet dni nad medianom a danou poziciou\n" + ...
    "4 - Najhorsi a najlepsi den v danom casovom rozmedzi\n" + ...
    "5 - Najhorsi a najlepsi casovy rozsah za celu dobu\n" + ...
    "6 - Najvacsia a najmensia pozadovana hodnota zvysujucej sa rychlosti (pocet dni)\n" + ...
    "7 - Vystyp\n" + ...
    "Vasa volba je tu: ";

MenuAsk = "1 - PocetpotvrdenychPCRtestami\n" + ...
    "2 - DennychPCRtesend_datev\n" + ...
    "3 - DennychPCRprirastkov\n" + ...
    "4 - Pocetumrti\n" + ...
    "5 - AgTests\n" + ...
    "6 - AgPosit\n" + ...
    "7 - Pocethospitalizovanych\n" + ...
    "Vasa volba je tu: ";
